export const BIBLE_PASSPORT_PRELOAD_VERSION = 1;

export const BIBLE_PASSPORT_VERSES = [
  {
    id: "passport-2026-01",
    month: 1,
    year: 2026,
    theme: "Spiritual Armor / 屬靈的軍裝",
    reference: "Ephesians 6:12-18 / 以弗所書 6:12-18",
    englishText: "6:12 For we do not wrestle against flesh and blood, but against the rulers, against the authorities, against the cosmic powers over this present darkness, against the spiritual forces of evil in the heavenly places.\n6:13 Therefore take up the whole armor of God, that you may be able to withstand in the evil day, and having done all, to stand firm.\n6:14 Stand therefore, having fastened on the belt of truth, and having put on the breastplate of righteousness,\n6:15 and, as shoes for your feet, having put on the readiness given by the gospel of peace.\n6:16 In all circumstances take up the shield of faith, with which you can extinguish all the flaming darts of the evil one;\n6:17 and take the helmet of salvation, and the sword of the Spirit, which is the word of God,\n6:18 praying at all times in the Spirit, with all prayer and supplication. To that end, keep alert with all perseverance, making supplication for all the saints.",
    chineseText: "6:12 因我們並不是與屬血氣的爭戰，乃是與那些執政的、掌權的、管轄這幽暗世界的，以及天空屬靈氣的惡魔爭戰。\n6:13 所以，要拿起神所賜的全副軍裝，好在磨難的日子抵擋仇敵，並且成就了一切，還能站立得住。\n6:14 所以要站穩了，用真理當作帶子束腰，用公義當作護心鏡遮胸，\n6:15 又用平安的福音當作預備走路的鞋穿在腳上。\n6:16 此外，又拿著信德當作籐牌，可以滅盡那惡者一切的火箭；\n6:17 並戴上救恩的頭盔，拿著聖靈的寶劍，就是神的道；\n6:18 靠著聖靈，隨時多方禱告祈求；並要在此儆醒不倦，為眾聖徒祈求。",
    sourcePage: 4,
  },
  {
    id: "passport-2026-02",
    month: 2,
    year: 2026,
    theme: "Christlike / 效法基督",
    reference: "Philippians 3:10-14 / 腓立比書 3:10-14",
    englishText: "3:10 that I may know him and the power of his resurrection, and may share his sufferings, becoming like him in his death,\n3:11 that by any means possible I may attain the resurrection from the dead.\n3:12 Not that I have already obtained this or am already perfect, but I press on to make it my own, because Christ Jesus has made me his own.\n3:13 Brothers, I do not consider that I have made it my own. But one thing I do: forgetting what lies behind and straining forward to what lies ahead,\n3:14 I press on toward the goal for the prize of the upward call of God in Christ Jesus.",
    chineseText: "3:10 使我認識基督，曉得他復活的大能，並且曉得和他一同受苦，效法他的死，\n3:11 或者我也得以從死裡復活。\n3:12 這不是說我已經得著了，已經完全了；我乃是竭力追求，或者可以得著基督耶穌所以得著我的。\n3:13 弟兄們，我不是以為自己已經得著了；我只有一件事，就是忘記背後，努力面前的，\n3:14 向著標竿直跑，要得神在基督耶穌裡從上面召我來得的獎賞。",
    sourcePage: 6,
  },
  {
    id: "passport-2026-03",
    month: 3,
    year: 2026,
    theme: "Beatitude / 八福",
    reference: "Matthew 5:3-10 / 馬太福音 5:3-10",
    englishText: "5:3 “Blessed are the poor in spirit, for theirs is the kingdom of heaven.\n5:4 “Blessed are those who mourn, for they shall be comforted.\n5:5 “Blessed are the meek, for they shall inherit the earth.\n5:6 “Blessed are those who hunger and thirst for righteousness, for they shall be satisfied.\n5:7 “Blessed are the merciful, for they shall receive mercy.\n5:8 “Blessed are the pure in heart, for they shall see God.\n5:9 “Blessed are the peacemakers, for they shall be called sons of God.\n5:10 “Blessed are those who are persecuted for righteousness’ sake, for theirs is the kingdom of heaven.",
    chineseText: "5:3 虛心的人有福了！因為天國是他們的。\n5:4 哀慟的人有福了！因為他們必得安慰。\n5:5 溫柔的人有福了！因為他們必承受地土。\n5:6 飢渴慕義的人有福了！因為他們必得飽足。\n5:7 憐恤人的人有福了！因為他們必蒙憐恤。\n5:8 清心的人有福了！因為他們必得見神。\n5:9 使人和睦的人有福了！因為他們必稱為神的兒子。\n5:10 為義受逼迫的人有福了！因為天國是他們的。",
    sourcePage: 8,
  },
  {
    id: "passport-2026-04",
    month: 4,
    year: 2026,
    theme: "Suffering Savior / 受苦的救主",
    reference: "1 Peter 2:21-25 / 彼得前書 2:21-25",
    englishText: "2:21 For to this you have been called, because Christ also suffered for you, leaving you an example, so that you might follow in his steps.\n2:22 He committed no sin, neither was deceit found in his mouth.\n2:23 When he was reviled, he did not revile in return; when he suffered, he did not threaten, but continued entrusting himself to him who judges justly.\n2:24 He himself bore our sins in his body on the tree, that we might die to sin and live to righteousness. By his wounds you have been healed.\n2:25 For you were straying like sheep, but have now returned to the Shepherd and Overseer of your souls.",
    chineseText: "2:21 你們蒙召原是為此；因基督也為你們受過苦，給你們留下榜樣，叫你們跟隨他的腳蹤行。\n2:22 他並沒有犯罪，口裡也沒有詭詐。\n2:23 他被罵不還口；受害不說威嚇的話，只將自己交託那按公義審判人的主。\n2:24 他被掛在木頭上，親身擔當了我們的罪，使我們既然在罪上死，就得以在義上活。因他受的鞭傷，你們便得了醫治。\n2:25 你們從前好像迷路的羊，如今卻歸到你們靈魂的牧人監督了。",
    sourcePage: 10,
  },
  {
    id: "passport-2026-05",
    month: 5,
    year: 2026,
    theme: "Church Vision / 教會異象",
    reference: "Revelation 22:1-5 / 啟示錄 22:1-5",
    englishText: "22:1 Then the angel showed me the river of the water of life, bright as crystal, flowing from the throne of God and of the Lamb\n22:2 through the middle of the street of the city; also, on either side of the river, the tree of life with its twelve kinds of fruit, yielding its fruit each month. The leaves of the tree were for the healing of the nations.\n22:3 No longer will there be anything accursed, but the throne of God and of the Lamb will be in it, and his servants will worship him.\n22:4 They will see his face, and his name will be on their foreheads.\n22:5 And night will be no more. They will need no light of lamp or sun, for the Lord God will be their light, and they will reign forever and ever.",
    chineseText: "22:1 天使又指示我在城內街道當中一道生命水的河，明亮如水晶，從神和羔羊的寶座流出來。\n22:2 在河這邊與那邊有生命樹，結十二樣果子，每月都結果子；樹上的葉子乃為醫治萬民。\n22:3 以後再沒有咒詛；在城裡有神和羔羊的寶座；他的僕人都要事奉他，\n22:4 也要見他的面。他的名字必寫在他們的額上。\n22:5 不再有黑夜；他們也不用燈光、日光，因為主神要光照他們。他們要作王，直到永永遠遠。",
    sourcePage: 12,
  },
  {
    id: "passport-2026-06",
    month: 6,
    year: 2026,
    theme: "Empowerment / 成全聖徒",
    reference: "Ephesians 4:11-16 / 以弗所書 4:11-16",
    englishText: "4:11 And he gave the apostles, the prophets, the evangelists, the shepherds and teachers,\n4:12 to equip the saints for the work of ministry, for building up the body of Christ,\n4:13 until we all attain to the unity of the faith and of the knowledge of the Son of God, to mature manhood, to the measure of the stature of the fullness of Christ,\n4:14 so that we may no longer be children, tossed to and fro by the waves and carried about by every wind of doctrine, by human cunning, by craftiness in deceitful schemes.\n4:15 Rather, speaking the truth in love, we are to grow up in every way into him who is the head, into Christ,\n4:16 from whom the whole body, joined and held together by every joint with which it is equipped, when each part is working properly, makes the body grow so that it builds itself up in love.",
    chineseText: "4:11 他所賜的，有使徒，有先知，有傳福音的，有牧師和教師，\n4:12 為要成全聖徒，各盡其職，建立基督的身體，\n4:13 直等到我們眾人在真道上同歸於一，認識神的兒子，得以長大成人，滿有基督長成的身量，\n4:14 使我們不再作小孩子，中了人的詭計和欺騙的法術，被一切異教之風搖動，飄來飄去，就隨從各樣的異端；\n4:15 惟用愛心說誠實話，凡事長進，連於元首基督，\n4:16 全身都靠他聯絡得合式，百節各按各職，照著各體的功用彼此相助，便叫身體漸漸增長，在愛中建立自己。",
    sourcePage: 14,
  },
  {
    id: "passport-2026-07",
    month: 7,
    year: 2026,
    theme: "Partnership / 團隊事奉",
    reference: "Philippians 2:1-5 / 腓立比書 2:1-5",
    englishText: "2:1 So if there is any encouragement in Christ, any comfort from love, any participation in the Spirit, any affection and sympathy,\n2:2 complete my joy by being of the same mind, having the same love, being in full accord and of one mind.\n2:3 Do nothing from selfish ambition or conceit, but in humility count others more significant than yourselves.\n2:4 Let each of you look not only to his own interests, but also to the interests of others.\n2:5 Have this mind among yourselves, which is yours in Christ Jesus.",
    chineseText: "2:1 所以，在基督裡若有甚麼勸勉，愛心有甚麼安慰，聖靈有甚麼交通，心中有甚麼慈悲憐憫，\n2:2 你們就要意念相同，愛心相同，有一樣的心思，有一樣的意念，使我的喜樂可以滿足。\n2:3 凡事不可結黨，不可貪圖虛浮的榮耀；只要存心謙卑，各人看別人比自己強。\n2:4 各人不要單顧自己的事，也要顧別人的事。\n2:5 你們當以基督耶穌的心為心：",
    sourcePage: 16,
  },
  {
    id: "passport-2026-08",
    month: 8,
    year: 2026,
    theme: "Faith / 信心跨越",
    reference: "Hebrews 11:1-6 / 希伯來書 11:1-6",
    englishText: "11:1 Now faith is the assurance of things hoped for, the conviction of things not seen.\n11:2 For by it the people of old received their commendation.\n11:3 By faith we understand that the universe was created by the word of God, so that what is seen was not made out of things that are visible.\n11:4 By faith Abel offered to God a more acceptable sacrifice than Cain, through which he was commended as righteous, God commending him by accepting his gifts. And through his faith, though he died, he still speaks.\n11:5 By faith Enoch was taken up so that he should not see death, and he was not found, because God had taken him. Now before he was taken he was commended as having pleased God.\n11:6 And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.",
    chineseText: "11:1 信就是所望之事的實底，是未見之事的確據。\n11:2 古人在這信上得了美好的證據。\n11:3 我們因著信，就知道諸世界是藉神話造成的；這樣，所看見的，並不是從顯然之物造出來的。\n11:4 亞伯因著信，獻祭與神，比該隱所獻的更美，因此便得了稱義的見證，就是神指他禮物作的見證。他雖然死了，卻因這信，仍舊說話。\n11:5 以諾因著信，被接去，不至於見死，人也找不著他，因為神已經把他接去了；只是他被接去以先，已經得了神喜悅他的明證。\n11:6 人非有信，就不能得神的喜悅；因為到神面前來的人必須信有神，且信他賞賜那尋求他的人。",
    sourcePage: 18,
  },
  {
    id: "passport-2026-09",
    month: 9,
    year: 2026,
    theme: "Innovation / 不斷更新",
    reference: "Isaiah 43:15-19 / 以賽亞書 43:15-19",
    englishText: "43:15 I am the Lord, your Holy One, the Creator of Israel, your King.\n43:16 Thus says the Lord, who makes a way in the sea, a path in the mighty waters,\n43:17 who brings forth chariot and horse, army and warrior; they lie down, they cannot rise, they are extinguished, quenched like a wick:\n43:18 “Remember not the former things, nor consider the things of old.\n43:19 Behold, I am doing a new thing; now it springs forth, do you not perceive it? I will make a way in the wilderness and rivers in the desert.",
    chineseText: "43:15 我是耶和華─你們的聖者，是創造以色列的，是你們的君王。\n43:16 耶和華在滄海中開道，在大水中開路，\n43:17 使車輛、馬匹、軍兵、勇士都出來，一同躺下，不再起來；他們滅沒，好像熄滅的燈火。\n43:18 耶和華如此說：你們不要記念從前的事，也不要思想古時的事。\n43:19 看哪，我要做一件新事；如今要發現，你們豈不知道麼？我必在曠野開道路，在沙漠開江河。",
    sourcePage: 20,
  },
  {
    id: "passport-2026-10",
    month: 10,
    year: 2026,
    theme: "Generosity / 慷慨樂施",
    reference: "2 Corinthians 9:6-11 / 哥林多後書 9:6-11",
    englishText: "9:6 The point is this: whoever sows sparingly will also reap sparingly, and whoever sows bountifully will also reap bountifully.\n9:7 Each one must give as he has decided in his heart, not reluctantly or under compulsion, for God loves a cheerful giver.\n9:8 And God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work.\n9:9 As it is written, “He has distributed freely, he has given to the poor; his righteousness endures forever.”\n9:10 He who supplies seed to the sower and bread for food will supply and multiply your seed for sowing and increase the harvest of your righteousness.\n9:11 You will be enriched in every way to be generous in every way, which through us will produce thanksgiving to God.",
    chineseText: "9:6 少種的少收，多種的多收，這話是真的。\n9:7 各人要隨本心所酌定的，不要作難，不要勉強，因為捐得樂意的人是神所喜愛的。\n9:8 神能將各樣的恩惠多多的加給你們，使你們凡事常常充足，能多行各樣善事。\n9:9 如經上所記：他施捨錢財，賙濟貧窮；他的仁義存到永遠。\n9:10 那賜種給撒種的，賜糧給人吃的，必多多加給你們種地的種子，又增添你們仁義的果子；\n9:11 叫你們凡事富足，可以多多施捨，就藉著我們使感謝歸於神。",
    sourcePage: 22,
  },
  {
    id: "passport-2026-11",
    month: 11,
    year: 2026,
    theme: "Trust & Follow / 信靠跟隨",
    reference: "Psalm 23:1-6 / 詩篇 23:1-6",
    englishText: "23:1 The Lord is my shepherd; I shall not want.\n23:2 He makes me lie down in green pastures. He leads me beside still waters.\n23:3 He restores my soul. He leads me in paths of righteousness for his name’s sake.\n23:4 Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me; your rod and your staff, they comfort me.\n23:5 You prepare a table before me in the presence of my enemies; you anoint my head with oil; my cup overflows.\n23:6 Surely goodness and mercy shall follow me all the days of my life, and I shall dwell in the house of the Lord forever.",
    chineseText: "23:1 耶和華是我的牧者，我必不致缺乏。\n23:2 他使我躺臥在青草地上，領我在可安歇的水邊。\n23:3 他使我的靈魂甦醒，為自己的名引導我走義路。\n23:4 我雖然行過死蔭的幽谷，也不怕遭害，因為你與我同在；你的杖，你的竿，都安慰我。\n23:5 在我敵人面前，你為我擺設筵席；你用油膏了我的頭，使我的福杯滿溢。\n23:6 我一生一世必有恩惠慈愛隨著我；我且要住在耶和華的殿中，直到永遠。",
    sourcePage: 24,
  },
  {
    id: "passport-2026-12",
    month: 12,
    year: 2026,
    theme: "The Lord’s Prayer / 主禱文",
    reference: "Matthew 6:9-13 / 馬太福音 6:9-13",
    englishText: "6:9 Pray then like this: “Our Father in heaven, hallowed be your name.\n6:10 Your kingdom come, your will be done, on earth as it is in heaven.\n6:11 Give us this day our daily bread,\n6:12 and forgive us our debts, as we also have forgiven our debtors.\n6:13 And lead us not into temptation, but deliver us from evil.",
    chineseText: "6:9 所以，你們禱告要這樣說：我們在天上的父：願人都尊你的名為聖。\n6:10 願你的國降臨；願你的旨意行在地上，如同行在天上。\n6:11 我們日用的飲食，今日賜給我們。\n6:12 免我們的債，如同我們免了人的債。\n6:13 不叫我們遇見試探；救我們脫離兇惡。因為國度、權柄、榮耀，全是你的，直到永遠。阿們！",
    sourcePage: 26,
  },
];
